"""
Django settings for ACL project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import importlib
import sys


load_dotenv = lambda *_args, **_kwargs: False  # type: ignore
_dotenv_spec = importlib.util.find_spec("dotenv")
if _dotenv_spec is not None:  # pragma: no cover
    load_dotenv = importlib.import_module("dotenv").load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY", "django-insecure-m(=06!thl^jj4qg&=s@z&gw)47$9@4hw&ss_mh(4k9wi^64(oz"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [host.strip() for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aclcore',
    'base',
    'user',
    'utils',
]

from ACL.middlewares_config import MIDDLEWARE

ROOT_URLCONF = 'ACL.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ACL.wsgi.application'


DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql_psycopg2"),
        "NAME": os.getenv("DB_NAME", "auth"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "1234"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


REDIS_URL = os.getenv("REDIS_URL")
if not REDIS_URL:
    redis_host = os.getenv("REDIS_HOST", "127.0.0.1")
    redis_port = os.getenv("REDIS_PORT", "6379")
    redis_db = os.getenv("REDIS_DB", "0")
    redis_username = os.getenv("REDIS_USERNAME", "")
    redis_password = os.getenv("REDIS_PASSWORD", "")

    credentials = ""
    if redis_username or redis_password:
        username_part = f"{redis_username}:" if redis_username else ""
        password_part = redis_password if redis_password else ""
        credentials = f"{username_part}{password_part}@"

    REDIS_URL = f"redis://{credentials}{redis_host}:{redis_port}/{redis_db}"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": os.getenv("REDIS_PASSWORD") or None,
        },
        "TIMEOUT": None,
    }
}

# Use in-memory cache during tests unless explicitly overridden
if "test" in sys.argv and os.getenv("USE_REDIS_IN_TESTS", "").lower() not in {"1", "true", "yes"}:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "acl-test-cache",
            "TIMEOUT": None,
        }
    }

# ACLCore defaults
ACLCORE_DEFAULT_APPLICATION = os.getenv("ACLCORE_DEFAULT_APPLICATION", None)
ACLCORE_CACHE_TTL_SECONDS = int(os.getenv("ACLCORE_CACHE_TTL_SECONDS", "3600"))
ACLCORE_BYPASS_PREFIXES = [p.strip() for p in os.getenv("ACLCORE_BYPASS_PREFIXES", "/health,/static,/media,/admin").split(",") if p.strip()]
ACLCORE_USER_ID_HEADER = os.getenv("ACLCORE_USER_ID_HEADER", "HTTP_X_USER_ID")
ACLCORE_APPLICATION_HEADER = os.getenv("ACLCORE_APPLICATION_HEADER", "HTTP_X_ACL_APP")
ACLCORE_LOG_SAMPLING_RATE = float(os.getenv("ACLCORE_LOG_SAMPLING_RATE", "1.0"))

SESSION_ENGINE = os.getenv("DJANGO_SESSION_ENGINE", "django.contrib.sessions.backends.cache")
SESSION_CACHE_ALIAS = "default"

JWT_ACCESS_SECRET = os.getenv("JWT_ACCESS_SECRET", SECRET_KEY)
JWT_ACCESS_TOKEN_LIFETIME = timedelta(
    seconds=int(os.getenv("JWT_ACCESS_TOKEN_LIFETIME_SECONDS", os.getenv("JWT_ACCESS_TOKEN_LIFETIME", "900")))
)

ACL_CACHE_TTL = int(os.getenv("ACL_CACHE_TTL", "3600"))
ACL_ENDPOINT_APP = os.getenv("ACL_ENDPOINT_APP", "utils")
ACL_ENDPOINT_MODEL = os.getenv("ACL_ENDPOINT_MODEL", "Endpoint")
ADMIN_API_PREFIX = os.getenv("ADMIN_API_PREFIX", "/api/admin/")
ADMIN_LOGIN_ATTEMPT_LIMIT = int(os.getenv("ADMIN_LOGIN_ATTEMPT_LIMIT", "5"))
ADMIN_LOGIN_BLOCK_SECONDS = int(os.getenv("ADMIN_LOGIN_BLOCK_SECONDS", str(5 * 60)))
ADMIN_RATE_LIMIT_REQUESTS = int(os.getenv("ADMIN_RATE_LIMIT_REQUESTS", "180"))
ADMIN_RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("ADMIN_RATE_LIMIT_WINDOW_SECONDS", "60"))

ACL_METRIC_DEFAULT_TTL = int(os.getenv("ACL_METRIC_DEFAULT_TTL", "3600"))

# Auth strategy flag (Session-only by default)
ADMIN_SESSION_ONLY_AUTH = os.getenv("ADMIN_SESSION_ONLY_AUTH", "True").lower() in {"1", "true", "yes"}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
