# Generated by Django 5.1.3 on 2025-11-16 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=16, unique=True)),
                ('encoded', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Method Encoding',
                'verbose_name_plural': 'Method Encodings',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.CharField(db_index=True, max_length=100)),
                ('path_pattern', models.CharField(db_index=True, max_length=300, unique=True)),
                ('method', models.CharField(db_index=True, max_length=16)),
                ('action', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'Endpoints',
                'indexes': [models.Index(fields=['service', 'method'], name='utils_endpo_service_17c575_idx')],
            },
        ),
        migrations.CreateModel(
            name='ACLRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('SuperUser', 'Super admin'), ('Admin', 'Admin'), ('ApiKey', 'API key')], db_index=True, max_length=50, null=True)),
                ('allow', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl_rules', to='user.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl_rules', to='user.staff')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_rules', to='utils.endpoint')),
            ],
            options={
                'verbose_name': 'ACL Rule',
                'verbose_name_plural': 'ACL Rules',
                'ordering': ['-priority', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('role__isnull', False), ('team__isnull', False), _connector='OR'), name='aclrule_subject_not_null')],
            },
        ),
    ]
