# Generated by Django 5.1.3 on 2025-11-16 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACLApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ACLCacheEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('route_hash', models.CharField(db_index=True, max_length=200)),
                ('is_allowed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'route_hash'], name='aclcore_acl_user_id_fd9b1d_idx'), models.Index(fields=['expires_at'], name='aclcore_acl_expires_0703bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ACLPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='aclcore.aclapplication')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ACLRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('is_super_role', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='aclcore.aclapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ACLRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('method', models.CharField(db_index=True, max_length=16)),
                ('normalized_path', models.CharField(blank=True, db_index=True, max_length=320, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_ignored', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='aclcore.aclapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ACLRoleRoutePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_permissions', to='aclcore.aclrole')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='aclcore.aclroute')),
            ],
        ),
        migrations.CreateModel(
            name='ACLAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('method', models.CharField(db_index=True, max_length=16)),
                ('allowed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='aclcore.aclroute')),
            ],
        ),
        migrations.CreateModel(
            name='ACLUserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='aclcore.aclapplication')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='aclcore.aclrole')),
            ],
        ),
        migrations.AddIndex(
            model_name='aclrole',
            index=models.Index(fields=['application', 'name'], name='aclcore_acl_applica_088414_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aclrole',
            unique_together={('application', 'name')},
        ),
        migrations.AddIndex(
            model_name='aclroute',
            index=models.Index(fields=['application', 'method'], name='aclcore_acl_applica_34bdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='aclroute',
            index=models.Index(fields=['application', 'normalized_path'], name='aclcore_acl_applica_3f7ee8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aclroute',
            unique_together={('application', 'path', 'method')},
        ),
        migrations.AddIndex(
            model_name='aclroleroutepermission',
            index=models.Index(fields=['role', 'route'], name='aclcore_acl_role_id_d97374_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aclroleroutepermission',
            unique_together={('role', 'route')},
        ),
        migrations.AddIndex(
            model_name='aclaccesslog',
            index=models.Index(fields=['user_id', 'timestamp'], name='aclcore_acl_user_id_1d0234_idx'),
        ),
        migrations.AddIndex(
            model_name='aclaccesslog',
            index=models.Index(fields=['method', 'timestamp'], name='aclcore_acl_method_a21307_idx'),
        ),
        migrations.AddIndex(
            model_name='acluserrole',
            index=models.Index(fields=['user_id', 'application'], name='aclcore_acl_user_id_d08b0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acluserrole',
            unique_together={('user_id', 'application', 'role')},
        ),
    ]
