# Generated by Django 5.1.3 on 2025-11-16 09:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_en', models.CharField(blank=True, choices=[('default', 'Default'), ('devops', 'DevOps'), ('developer', 'Developer'), ('managers', 'Managers'), ('general_manager', 'General manager'), ('general_director', 'General director'), ('general_secretary', 'General secretary')], db_index=True, max_length=50, null=True, verbose_name='english name')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number format is invalid.', regex='^0[0-9]{10}$')])),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Last name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_index=True, null=True, verbose_name='Gender')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('first_login', models.DateTimeField(blank=True, null=True, verbose_name='First login')),
                ('national_code', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='National code')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Postal code')),
                ('bank_account', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Bank account')),
                ('extra_info', models.JSONField(blank=True, null=True, verbose_name='Extra information')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('route_method', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Last name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_index=True, null=True, verbose_name='Gender')),
                ('phone_number', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number format is invalid.', regex='^0[0-9]{10}$')])),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email')),
                ('role', models.CharField(blank=True, choices=[('SuperUser', 'Super admin'), ('Admin', 'Admin'), ('ApiKey', 'API key')], db_index=True, max_length=50, null=True, verbose_name='Role')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('team', models.ManyToManyField(db_index=True, to='user.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
